/* attributes.h
 * =====================================================
 * TFTP attribute and endpoint definitions.
 * -----------------------------------------------------
 * Author: Connor Newton
 *   Date: November 24, 2014
 */

#ifndef TFTP_ATTRIBUTES
#define TFTP_ATTRIBUTES

#include "telemetry/tftp/core.h"
#include "telemetry/tftp/types.h"
#include "telemetry/tftp/endpoint.h"

/* Linescan attributes */
#define TFTP_LINESCAN0
#define TFTP_LINESCAN0_CODE 0x01
#define TFTP_LINESCAN0_ENDPOINT TFTP_ENDPOINT_SYM(TFTP_LINESCAN0)
 		TFTP_ENDPOINT_PUSH(TFTP_LINESCAN0_ENDPOINT, TFTP_LINESCAN0_CODE, TFTP_LINESCAN_TYPE, TFTP_LINESCAN_SIZE)
 		
#define TFTP_LINESCAN1
#define TFTP_LINESCAN1_CODE 0x02
#define TFTP_LINESCAN1_ENDPOINT TFTP_ENDPOINT_SYM(TFTP_LINESCAN1)
 		TFTP_ENDPOINT_PUSH(TFTP_LINESCAN1_ENDPOINT, TFTP_LINESCAN1_CODE, TFTP_LINESCAN_TYPE, TFTP_LINESCAN_SIZE)

/* Angular velocity attributes */
#define TFTP_W_FL
#define TFTP_W_FL_CODE 0x03
#define TFTP_W_FL_ENDPOINT TFTP_ENDPOINT_SYM(TFTP_W_FL)
 		TFTP_ENDPOINT_PUSH(TFTP_W_FL_ENDPOINT, TFTP_W_FL_CODE, TFTP_ANGULAR_VELOCITY_TYPE, TFTP_ANGULAR_VELOCITY_SIZE)

#define TFTP_W_FR
#define TFTP_W_FR_CODE 0x04
#define TFTP_W_FR_ENDPOINT TFTP_ENDPOINT_SYM(TFTP_W_FR)
 		TFTP_ENDPOINT_PUSH(TFTP_W_FR_ENDPOINT, TFTP_W_FR_CODE, TFTP_ANGULAR_VELOCITY_TYPE, TFTP_ANGULAR_VELOCITY_SIZE)

#define TFTP_W_RL
#define TFTP_W_RL_CODE 0x05
#define TFTP_W_RL_ENDPOINT TFTP_ENDPOINT_SYM(TFTP_W_RL)
 		TFTP_ENDPOINT_PUSH(TFTP_W_RL_ENDPOINT, TFTP_W_RL_CODE, TFTP_ANGULAR_VELOCITY_TYPE, TFTP_ANGULAR_VELOCITY_SIZE)

#define TFTP_W_RR
#define TFTP_W_RR_CODE 0x06
#define TFTP_W_RR_ENDPOINT TFTP_ENDPOINT_SYM(TFTP_W_RR)
 		TFTP_ENDPOINT_PUSH(TFTP_W_RR_ENDPOINT, TFTP_W_RR_CODE, TFTP_ANGULAR_VELOCITY_TYPE, TFTP_ANGULAR_VELOCITY_SIZE)

/* Motor current attributes */
#define TFTP_I_RL
#define TFTP_I_RL_CODE 0x07
#define TFTP_I_RL_ENDPOINT TFTP_ENDPOINT_SYM(TFTP_I_RL)
 		TFTP_ENDPOINT_PUSH(TFTP_I_RL_ENDPOINT, TFTP_I_RL_CODE, TFTP_MOTOR_CURRENT_TYPE, TFTP_MOTOR_CURRENT_SIZE)

#define TFTP_I_RR
#define TFTP_I_RR_CODE 0x08
#define TFTP_I_RR_ENDPOINT TFTP_ENDPOINT_SYM(TFTP_I_RR)
 		TFTP_ENDPOINT_PUSH(TFTP_I_RR_ENDPOINT, TFTP_I_RR_CODE, TFTP_MOTOR_CURRENT_TYPE, TFTP_MOTOR_CURRENT_SIZE)

/* Motor torque attributes */
#define TFTP_T_RL
#define TFTP_T_RL_CODE 0x09
#define TFTP_T_RL_ENDPOINT TFTP_ENDPOINT_SYM(TFTP_T_RL)
 		TFTP_ENDPOINT_PUSH(TFTP_T_RL_ENDPOINT, TFTP_T_RL_CODE, TFTP_MOTOR_TORQUE_TYPE, TFTP_MOTOR_TORQUE_SIZE)

#define TFTP_T_RR
#define TFTP_T_RR_CODE 0x0A
#define TFTP_T_RR_ENDPOINT TFTP_ENDPOINT_SYM(TFTP_T_RR)
 		TFTP_ENDPOINT_PUSH(TFTP_T_RR_ENDPOINT, TFTP_T_RR_CODE, TFTP_MOTOR_TORQUE_TYPE, TFTP_MOTOR_TORQUE_SIZE)

/* Slip attributes */
#define TFTP_S_RL
#define TFTP_S_RL_CODE 0x0B
#define TFTP_S_RL_ENDPOINT TFTP_ENDPOINT_SYM(TFTP_S_RL)
 		TFTP_ENDPOINT_PUSH(TFTP_S_RL_ENDPOINT, TFTP_S_RL_CODE, TFTP_SLIP_TYPE, TFTP_SLIP_SIZE)

#define TFTP_S_RR
#define TFTP_S_RR_CODE 0x0C
#define TFTP_S_RR_ENDPOINT TFTP_ENDPOINT_SYM(TFTP_S_RR)
 		TFTP_ENDPOINT_PUSH(TFTP_S_RR_ENDPOINT, TFTP_S_RR_CODE, TFTP_SLIP_TYPE, TFTP_SLIP_SIZE)

/* Positioning state attributes */
#define TFTP_POSITIONING_STATE
#define TFTP_POSITIONING_STATE_CODE 0x0D
#define TFTP_POSITIONING_STATE_ENDPOINT TFTP_ENDPOINT_SYM(TFTP_POSITIONING_STATE)
 		TFTP_ENDPOINT_PUSH(TFTP_POSITIONING_STATE_ENDPOINT, TFTP_POSITIONING_STATE_CODE, TFTP_POSITIONING_STATE_TYPE, TFTP_POSITIONING_STATE_SIZE)

/* Line attributes */
#define TFTP_TARGET_LINE
#define TFTP_TARGET_LINE_CODE 0x0E
#define TFTP_TARGET_LINE_ENDPOINT TFTP_ENDPOINT_SYM(TFTP_TARGET_LINE)
 		TFTP_ENDPOINT_PUSH(TFTP_TARGET_LINE_ENDPOINT, TFTP_TARGET_LINE_CODE, TFTP_LINE_TYPE, TFTP_LINE_SIZE)

/* Track position attributes */
#define TFTP_TRACK_POSITION
#define TFTP_TRACK_POSITION_CODE 0x0F
#define TFTP_TRACK_POSITION_ENDPOINT TFTP_ENDPOINT_SYM(TFTP_TRACK_POSITION)
 		TFTP_ENDPOINT_PUSH(TFTP_TRACK_POSITION_ENDPOINT, TFTP_TRACK_POSITION_CODE, TFTP_TRACK_POSITION_TYPE, TFTP_TRACK_POSITION_CODE)

#endif //TFTP_ATTRIBUTES
