function gui = MotorSpeedControlLayout( gui, fig )
%VisionCurrentLayout Load a simple GUI window showing car vision and motor
%load current.
    
    gui = gui.addViews(...
        WheelSpeedView(gui.session, 'w_rl', 'figure', fig, 'position', [2,2,1]),...
        WheelSpeedView(gui.session, 'w_rr', 'figure', fig, 'position', [2,2,3]),...
        MotorDutyView(gui.session, 'D_rl', 'figure', fig, 'position', [2,2,2]),...
        MotorDutyView(gui.session, 'D_rr', 'figure', fig, 'position', [2,2,4])...
    );
end

