function gui = MotorSpeedControlLayout( gui, fig )
%VisionCurrentLayout Load a simple GUI window showing car vision and motor
%load current.
    
    gui = gui.addViews(...
        WheelSpeedView(gui.session, 'w_rl', 'figure', fig, 'position', [2,3,1]),...
        WheelSpeedView(gui.session, 'w_rr', 'figure', fig, 'position', [2,3,4]),...
        MotorDutyView(gui.session, 'D_rl', 'figure', fig, 'position', [2,3,2]),...
        MotorDutyView(gui.session, 'D_rr', 'figure', fig, 'position', [2,3,5]),...
        WheelSlipView(gui.session, 's_rl', 'figure', fig, 'position', [2,3,3]),...
        WheelSlipView(gui.session, 's_rr', 'figure', fig, 'position', [2,3,6])...
    );
end

