function gui = VisionLayout( gui, fig )
%VisionCurrentLayout Load a simple GUI window showing car vision and motor
%load current.
    
    gui = gui.addViews(...
        LinescanView(gui.session, 'linescan0', 'figure', fig, 'position', [2,2,1]),...
        TrackPositionView(gui.session, 'TrackPosition', 'figure', fig, 'position', [2,2,2]),...
        LinescanDerivativeView(gui.session, 'linescan0', 'figure', fig, 'position', [2,2,3]),...
        LinescanEdgeView(gui.session, 'linescan0', 'figure', fig, 'position', [2,2,4])...
    );
end

