classdef WheelSlipView < ChartView
    %MotorCurrentView
    
    methods
        % constructor
        function obj = WheelSlipView(session, attribute, varargin)
            
            % initialise view
            obj = obj@ChartView(...
                session,varargin{:}, ...
                'xlabel', 'Time (s)', ...
                'ylabel', 'Slip (ratio)', ...
                'ybotl', -0.4, ...
                'ybotu', -0.2, ...
                'ytopl', 0.2, ...
                'ytopu', 0.4 ...
                );
            
            % add series
            obj = obj.addSeries(@ChartSeries, attribute, 'label', 'Slip ratio');
        end
    end
end